export const CHANGE_LOADED_CONTACT = 'CHANGE_LOADED_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const CHANGE_CONTACT = 'CHANGE_CONTACT';
export const PAGE_LOAD = 'PAGE_LOAD';


export const GET_CONTACTS = 'GET_CONTACTS';